/**
 * Demo seeding.
 *
 * Deterministic: every row id is derived from a stable key, so re-running the
 * seed updates the same rows instead of duplicating them. Idempotent: by default
 * it does nothing when an organization already exists.
 */

import path from 'node:path';

import { hashPassword } from '../auth/password';
import { config } from '../config';
import { seedId } from '../lib/ids';
import { writeUpload } from '../lib/files';
import { addDays, todayInTimezone, type IsoDate } from '../../shared/dates';
import { parseAmountToCents } from '../../shared/money';
import type { Db } from './connection';
import { DEMO_USERS, DEMO_PASSWORD } from './demo-accounts';
import { DEMO_FUNDERS, DEMO_GRANTS, DEMO_ORGS, type EvidenceSpec, type GrantSpec } from './demo-data';
import { buildDemoPdf } from './demo-pdf';
import { buildDemoXlsx } from './demo-xlsx';

export interface SeedResult {
  seeded: boolean;
  organizations: number;
  users: number;
  funders: number;
  grants: number;
  tasks: number;
  milestones: number;
  budgetLines: number;
  documents: number;
  comments: number;
  activities: number;
}

const orgId = (key: string) => seedId('org', key);
const userId = (key: string) => seedId('usr', key);
const funderId = (key: string) => seedId('fnd', key);
const grantId = (key: string) => seedId('gr', key);
const contactId = (funderKey: string, name: string) => seedId('fct', funderKey, name);
const taskId = (grantKey: string, key: string) => seedId('tsk', grantKey, key);
const milestoneId = (grantKey: string, key: string) => seedId('mil', grantKey, key);
const budgetId = (grantKey: string, category: string) => seedId('bud', grantKey, category);
const documentId = (grantKey: string, name: string) => seedId('doc', grantKey, name);
const commentId = (grantKey: string, index: number) => seedId('cmt', grantKey, String(index));
const membershipId = (userKey: string, orgKey: string) => seedId('mem', userKey, orgKey);

function isoAt(daysAgo: number, reference: Date): string {
  return new Date(reference.getTime() - daysAgo * 86_400_000).toISOString();
}

function evidenceBytes(evidence: EvidenceSpec, grant: GrantSpec): Buffer {
  const ext = path.extname(evidence.name).toLowerCase();
  if (ext === '.xlsx') {
    const rows: Array<Array<string | number>> = [
      [grant.title],
      [evidence.name],
      [],
      ['Item', 'Detail'],
      ...evidence.summary.map((line, index) => [`Note ${index + 1}`, line] as Array<string | number>),
      [],
      ['Category', 'Planned (USD)', 'Spent (USD)'],
      ...grant.budget.map((b) => [b.category, Number(b.planned), Number(b.spent)] as Array<string | number>),
    ];
    return buildDemoXlsx('Evidence', rows);
  }
  return buildDemoPdf(evidence.name.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' '), [
    `Grant: ${grant.title}`,
    `Program: ${grant.program}`,
    '',
    ...evidence.summary,
    '',
    'Demo evidence document generated by GrantConsole for local demonstration.',
  ]);
}

function mimeFor(filename: string): string {
  const ext = path.extname(filename).toLowerCase();
  if (ext === '.xlsx') return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
  if (ext === '.docx') return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  return 'application/pdf';
}

export async function seedDemoData(
  db: Db,
  options: { force?: boolean; uploadsDir?: string; now?: Date } = {},
): Promise<SeedResult> {
  const existing = (db.prepare('SELECT COUNT(*) AS count FROM organizations').get() as { count: number }).count;
  if (existing > 0 && !options.force) {
    return { ...countRows(db), seeded: false };
  }

  const now = options.now ?? new Date();
  const uploadsDir = options.uploadsDir ?? config.uploadsDir;
  const nowIso = now.toISOString();

  // Password hashing is async, so it happens before the synchronous transaction.
  const passwordHash = await hashPassword(DEMO_PASSWORD);

  const orgToday = new Map<string, IsoDate>();
  for (const org of DEMO_ORGS) {
    orgToday.set(org.key, todayInTimezone(org.timezone, now));
  }

  // Generate evidence files first; a failed write must not leave orphan rows.
  const evidenceFiles: Array<{ storageKey: string; bytes: Buffer; grantKey: string; evidence: EvidenceSpec }> = [];
  for (const grant of DEMO_GRANTS) {
    for (const evidence of grant.evidence) {
      const bytes = evidenceBytes(evidence, grant);
      const storageKey = path.posix.join(
        orgId(grant.orgKey).replace(/[^A-Za-z0-9_-]/g, ''),
        `${seedId('key', grant.key, evidence.name)}${path.extname(evidence.name).toLowerCase()}`,
      );
      evidenceFiles.push({ storageKey, bytes, grantKey: grant.key, evidence });
    }
  }
  for (const file of evidenceFiles) {
    writeUpload(file.storageKey, file.bytes, uploadsDir);
  }

  const run = db.transaction(() => {
    /* ------------------------------------------------------- organizations */
    const upsertOrg = db.prepare(
      `INSERT INTO organizations (id, name, slug, timezone, currency, fiscal_year_start_month, created_at, updated_at)
       VALUES (@id, @name, @slug, @timezone, @currency, @fiscalYearStartMonth, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET name = excluded.name, slug = excluded.slug, timezone = excluded.timezone,
         currency = excluded.currency, fiscal_year_start_month = excluded.fiscal_year_start_month,
         updated_at = excluded.updated_at`,
    );
    for (const org of DEMO_ORGS) {
      upsertOrg.run({
        id: orgId(org.key),
        name: org.name,
        slug: org.slug,
        timezone: org.timezone,
        currency: org.currency,
        fiscalYearStartMonth: org.fiscalYearStartMonth,
        createdAt: isoAt(400, now),
        updatedAt: nowIso,
      });
    }

    /* -------------------------------------------------- users + memberships */
    const upsertUser = db.prepare(
      `INSERT INTO users (id, name, email, password_hash, title, is_active, created_at)
       VALUES (@id, @name, @email, @passwordHash, @title, 1, @createdAt)
       ON CONFLICT(id) DO UPDATE SET name = excluded.name, email = excluded.email,
         password_hash = excluded.password_hash, title = excluded.title, is_active = 1`,
    );
    const upsertMembership = db.prepare(
      `INSERT INTO memberships (id, user_id, org_id, role, created_at)
       VALUES (@id, @userId, @orgId, @role, @createdAt)
       ON CONFLICT(id) DO UPDATE SET role = excluded.role`,
    );
    for (const user of DEMO_USERS) {
      upsertUser.run({
        id: userId(user.key),
        name: user.name,
        email: user.email,
        passwordHash,
        title: user.title,
        createdAt: isoAt(380, now),
      });
      for (const membership of user.memberships) {
        upsertMembership.run({
          id: membershipId(user.key, membership.orgKey),
          userId: userId(user.key),
          orgId: orgId(membership.orgKey),
          role: membership.role,
          createdAt: isoAt(378, now),
        });
      }
    }

    /* --------------------------------------------------- funders + contacts */
    const upsertFunder = db.prepare(
      `INSERT INTO funders (id, org_id, name, type, focus_areas, website, notes, archived, created_at, updated_at)
       VALUES (@id, @orgId, @name, @type, @focusAreas, @website, @notes, 0, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET name = excluded.name, type = excluded.type, focus_areas = excluded.focus_areas,
         website = excluded.website, notes = excluded.notes, updated_at = excluded.updated_at`,
    );
    const upsertContact = db.prepare(
      `INSERT INTO funder_contacts (id, org_id, funder_id, name, title, email, phone, notes, created_at, updated_at)
       VALUES (@id, @orgId, @funderId, @name, @title, @email, @phone, @notes, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET name = excluded.name, title = excluded.title, email = excluded.email,
         phone = excluded.phone, notes = excluded.notes, updated_at = excluded.updated_at`,
    );
    for (const funder of DEMO_FUNDERS) {
      upsertFunder.run({
        id: funderId(funder.key),
        orgId: orgId(funder.orgKey),
        name: funder.name,
        type: funder.type,
        focusAreas: funder.focusAreas.join('|'),
        website: funder.website,
        notes: funder.notes,
        createdAt: isoAt(360, now),
        updatedAt: nowIso,
      });
      for (const contact of funder.contacts) {
        upsertContact.run({
          id: contactId(funder.key, contact.name),
          orgId: orgId(funder.orgKey),
          funderId: funderId(funder.key),
          name: contact.name,
          title: contact.title,
          email: contact.email,
          phone: contact.phone,
          notes: contact.notes ?? null,
          createdAt: isoAt(358, now),
          updatedAt: nowIso,
        });
      }
    }

    /* ---------------------------------------------------------------- grants */
    const upsertGrant = db.prepare(
      `INSERT INTO grants (id, org_id, funder_id, owner_user_id, title, program, status, requested_cents,
          awarded_cents, currency, probability, purpose, requirements, next_action, notes, application_date,
          decision_date, start_date, end_date, renewal_date, closeout_date, archived, created_at, updated_at)
       VALUES (@id, @orgId, @funderId, @ownerUserId, @title, @program, @status, @requestedCents, @awardedCents,
          @currency, @probability, @purpose, @requirements, @nextAction, @notes, @applicationDate, @decisionDate,
          @startDate, @endDate, @renewalDate, @closeoutDate, 0, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET funder_id = excluded.funder_id, owner_user_id = excluded.owner_user_id,
         title = excluded.title, program = excluded.program, status = excluded.status,
         requested_cents = excluded.requested_cents, awarded_cents = excluded.awarded_cents,
         probability = excluded.probability, purpose = excluded.purpose, requirements = excluded.requirements,
         next_action = excluded.next_action, notes = excluded.notes, application_date = excluded.application_date,
         decision_date = excluded.decision_date, start_date = excluded.start_date, end_date = excluded.end_date,
         renewal_date = excluded.renewal_date, closeout_date = excluded.closeout_date, archived = 0,
         updated_at = excluded.updated_at`,
    );
    const upsertTask = db.prepare(
      `INSERT INTO tasks (id, org_id, grant_id, assignee_user_id, title, description, status, priority, due_date,
          completed_at, created_at, updated_at)
       VALUES (@id, @orgId, @grantId, @assigneeUserId, @title, @description, @status, @priority, @dueDate,
          @completedAt, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET assignee_user_id = excluded.assignee_user_id, title = excluded.title,
         description = excluded.description, status = excluded.status, priority = excluded.priority,
         due_date = excluded.due_date, completed_at = excluded.completed_at, updated_at = excluded.updated_at`,
    );
    const upsertMilestone = db.prepare(
      `INSERT INTO milestones (id, org_id, grant_id, type, title, due_date, status, submitted_at, completed_at,
          required_evidence_count, notes, created_at, updated_at)
       VALUES (@id, @orgId, @grantId, @type, @title, @dueDate, @status, @submittedAt, @completedAt,
          @requiredEvidenceCount, @notes, @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET type = excluded.type, title = excluded.title, due_date = excluded.due_date,
         status = excluded.status, submitted_at = excluded.submitted_at, completed_at = excluded.completed_at,
         required_evidence_count = excluded.required_evidence_count, notes = excluded.notes,
         updated_at = excluded.updated_at`,
    );
    const upsertBudget = db.prepare(
      `INSERT INTO budget_lines (id, org_id, grant_id, category, description, planned_cents, spent_cents,
          sort_order, created_at, updated_at)
       VALUES (@id, @orgId, @grantId, @category, @description, @plannedCents, @spentCents, @sortOrder,
          @createdAt, @updatedAt)
       ON CONFLICT(id) DO UPDATE SET category = excluded.category, description = excluded.description,
         planned_cents = excluded.planned_cents, spent_cents = excluded.spent_cents,
         sort_order = excluded.sort_order, updated_at = excluded.updated_at`,
    );
    const upsertDocument = db.prepare(
      `INSERT INTO documents (id, org_id, grant_id, milestone_id, uploaded_by, original_name, storage_key,
          doc_type, mime_type, size_bytes, created_at)
       VALUES (@id, @orgId, @grantId, @milestoneId, @uploadedBy, @originalName, @storageKey, @docType,
          @mimeType, @sizeBytes, @createdAt)
       ON CONFLICT(id) DO UPDATE SET milestone_id = excluded.milestone_id, doc_type = excluded.doc_type,
         storage_key = excluded.storage_key, mime_type = excluded.mime_type, size_bytes = excluded.size_bytes,
         created_at = excluded.created_at`,
    );
    const upsertComment = db.prepare(
      `INSERT INTO comments (id, org_id, grant_id, author_user_id, body, created_at)
       VALUES (@id, @orgId, @grantId, @authorUserId, @body, @createdAt)
       ON CONFLICT(id) DO UPDATE SET body = excluded.body, created_at = excluded.created_at`,
    );

    const filesByGrant = new Map<string, typeof evidenceFiles>();
    for (const file of evidenceFiles) {
      const list = filesByGrant.get(file.grantKey) ?? [];
      list.push(file);
      filesByGrant.set(file.grantKey, list);
    }

    for (const grant of DEMO_GRANTS) {
      const today = orgToday.get(grant.orgKey)!;
      const offsetDate = (offset: number | null): IsoDate | null => (offset === null ? null : addDays(today, offset));
      const createdAt = isoAt(Math.max(20, Math.abs(grant.applicationOffset ?? 60) + 4), now);

      upsertGrant.run({
        id: grantId(grant.key),
        orgId: orgId(grant.orgKey),
        funderId: funderId(grant.funderKey),
        ownerUserId: grant.ownerKey ? userId(grant.ownerKey) : null,
        title: grant.title,
        program: grant.program,
        status: grant.status,
        requestedCents: parseAmountToCents(grant.requested),
        awardedCents: parseAmountToCents(grant.awarded),
        currency: 'USD',
        probability: grant.probability,
        purpose: grant.purpose,
        requirements: grant.requirements,
        nextAction: grant.nextAction,
        notes: grant.notes ?? null,
        applicationDate: offsetDate(grant.applicationOffset),
        decisionDate: offsetDate(grant.decisionOffset),
        startDate: offsetDate(grant.startOffset),
        endDate: offsetDate(grant.endOffset),
        renewalDate: offsetDate(grant.renewalOffset),
        closeoutDate: offsetDate(grant.closeoutOffset),
        createdAt,
        updatedAt: isoAt(Math.floor(Math.abs(grant.key.length % 9)) + 1, now),
      });

      for (const task of grant.tasks) {
        upsertTask.run({
          id: taskId(grant.key, task.key),
          orgId: orgId(grant.orgKey),
          grantId: grantId(grant.key),
          assigneeUserId: task.assigneeKey ? userId(task.assigneeKey) : null,
          title: task.title,
          description: task.description ?? null,
          status: task.status,
          priority: task.priority,
          dueDate: task.dueOffset === null ? null : addDays(today, task.dueOffset),
          completedAt: task.status === 'DONE' ? isoAt(Math.abs(task.dueOffset ?? 5), now) : null,
          createdAt,
          updatedAt: isoAt(3, now),
        });
      }

      for (const milestone of grant.milestones) {
        const submitted = milestone.status === 'SUBMITTED' || milestone.status === 'COMPLETE';
        const completed = milestone.status === 'COMPLETE' || milestone.status === 'WAIVED';
        upsertMilestone.run({
          id: milestoneId(grant.key, milestone.key),
          orgId: orgId(grant.orgKey),
          grantId: grantId(grant.key),
          type: milestone.type,
          title: milestone.title,
          dueDate: addDays(today, milestone.dueOffset),
          status: milestone.status,
          submittedAt: submitted ? isoAt(Math.max(1, Math.abs(milestone.dueOffset)), now) : null,
          completedAt: completed ? isoAt(Math.max(1, Math.abs(milestone.dueOffset)), now) : null,
          requiredEvidenceCount: milestone.requiredEvidenceCount,
          notes: milestone.notes ?? null,
          createdAt,
          updatedAt: isoAt(4, now),
        });
      }

      grant.budget.forEach((line, index) => {
        upsertBudget.run({
          id: budgetId(grant.key, line.category),
          orgId: orgId(grant.orgKey),
          grantId: grantId(grant.key),
          category: line.category,
          description: line.description,
          plannedCents: parseAmountToCents(line.planned),
          spentCents: parseAmountToCents(line.spent),
          sortOrder: index,
          createdAt,
          updatedAt: isoAt(5, now),
        });
      });

      for (const file of filesByGrant.get(grant.key) ?? []) {
        upsertDocument.run({
          id: documentId(grant.key, file.evidence.name),
          orgId: orgId(grant.orgKey),
          grantId: grantId(grant.key),
          milestoneId: file.evidence.milestoneKey ? milestoneId(grant.key, file.evidence.milestoneKey) : null,
          uploadedBy: userId(file.evidence.uploaderKey),
          originalName: file.evidence.name,
          storageKey: file.storageKey,
          docType: file.evidence.docType,
          mimeType: mimeFor(file.evidence.name),
          sizeBytes: file.bytes.length,
          createdAt: isoAt(file.evidence.daysAgo, now),
        });
      }

      grant.comments.forEach((comment, index) => {
        upsertComment.run({
          id: commentId(grant.key, index),
          orgId: orgId(grant.orgKey),
          grantId: grantId(grant.key),
          authorUserId: userId(comment.authorKey),
          body: comment.body,
          createdAt: isoAt(comment.daysAgo, now),
        });
      });
    }

    /* -------------------------------------------------------------- activity */
    db.prepare('DELETE FROM activities').run();
    const insertActivity = db.prepare(
      `INSERT INTO activities (id, org_id, actor_user_id, entity_type, entity_id, grant_id, action, summary,
          metadata, created_at)
       VALUES (@id, @orgId, @actorUserId, @entityType, @entityId, @grantId, @action, @summary, @metadata, @createdAt)`,
    );

    for (const grant of DEMO_GRANTS) {
      const owner = grant.ownerKey ?? 'dana';
      insertActivity.run({
        id: seedId('act', grant.key, 'created'),
        orgId: orgId(grant.orgKey),
        actorUserId: userId(owner),
        entityType: 'GRANT',
        entityId: grantId(grant.key),
        grantId: grantId(grant.key),
        action: 'CREATED',
        summary: `Created grant “${grant.title}”`,
        metadata: JSON.stringify({ status: grant.status }),
        createdAt: isoAt(Math.max(30, Math.abs(grant.applicationOffset ?? 60)), now),
      });

      grant.comments.forEach((comment, index) => {
        insertActivity.run({
          id: seedId('act', grant.key, 'comment', String(index)),
          orgId: orgId(grant.orgKey),
          actorUserId: userId(comment.authorKey),
          entityType: 'COMMENT',
          entityId: commentId(grant.key, index),
          grantId: grantId(grant.key),
          action: 'CREATED',
          summary: 'Added a note',
          metadata: null,
          createdAt: isoAt(comment.daysAgo, now),
        });
      });

      for (const file of filesByGrant.get(grant.key) ?? []) {
        insertActivity.run({
          id: seedId('act', grant.key, 'doc', file.evidence.name),
          orgId: orgId(grant.orgKey),
          actorUserId: userId(file.evidence.uploaderKey),
          entityType: 'DOCUMENT',
          entityId: documentId(grant.key, file.evidence.name),
          grantId: grantId(grant.key),
          action: 'UPLOADED',
          summary: `Uploaded evidence “${file.evidence.name}”`,
          metadata: null,
          createdAt: isoAt(file.evidence.daysAgo, now),
        });
      }

      for (const milestone of grant.milestones) {
        if (milestone.status !== 'COMPLETE' && milestone.status !== 'SUBMITTED') continue;
        insertActivity.run({
          id: seedId('act', grant.key, 'mil', milestone.key),
          orgId: orgId(grant.orgKey),
          actorUserId: userId(grant.ownerKey ?? 'dana'),
          entityType: 'MILESTONE',
          entityId: milestoneId(grant.key, milestone.key),
          grantId: grantId(grant.key),
          action: 'STATUS_CHANGED',
          summary: `“${milestone.title}” marked ${milestone.status === 'COMPLETE' ? 'complete' : 'submitted'}`,
          metadata: null,
          createdAt: isoAt(Math.max(1, Math.abs(milestone.dueOffset)), now),
        });
      }
    }
  });

  run();
  return { ...countRows(db), seeded: true };
}

function countRows(db: Db): Omit<SeedResult, 'seeded'> {
  const count = (table: string) => (db.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get() as { count: number }).count;
  return {
    organizations: count('organizations'),
    users: count('users'),
    funders: count('funders'),
    grants: count('grants'),
    tasks: count('tasks'),
    milestones: count('milestones'),
    budgetLines: count('budget_lines'),
    documents: count('documents'),
    comments: count('comments'),
    activities: count('activities'),
  };
}

/** Stable id builders, exported for tests that assert seed determinism. */
export const DEMO_SEED_IDS = { orgId, userId, funderId, grantId };
